spring:
  application:
    name: practice-svc
  datasource:
    url: jdbc:h2:mem:practice-db
    #url: jdbc:h2:file:./practice-svc/.data/practice-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: practiceSvcHickariCP
      max-lifetime: 60000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:/sql/schema.sql
      data-locations: classpath:/sql/data.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9001
server:
  port: 8088

application:
  api:
    root: /rest

